apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-db
  annotations:
    metallb.universe.tf/address-pool: "metallb-dynamic"
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres-db
